export enum OrderMessage {
  ORDER_INITIATED = "ORDER_INITIATED",
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_PROCESSING = "ORDER_PROCESSING",
  ORDER_DELIVERED = "ORDER_DELIVERED",
  ORDER_CANCELLED = "ORDER_CANCELLED",
}

export enum RedisMessage {
  COD_ORDER = "COD_ORDER",
  PREPAID_ORDER = "PREPAID_ORDER",
}
